webtalk_init -webtalk_dir D:/DiplomskiHbbTV/realization/HbbTV_Test/HbbTV_Test.sim/sim_1/behav/xsim.dir/FlashTest_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul 04 14:55:19 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174110479_206666196_206649563_746" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "994cca83310a5e43bfe370c28f8e0a1b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "811531c13d77419ba82caf0e966c4130" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3990 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "31.60_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16120_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3458060585 -regid "174110479_206666196_206649563_746" -xml D:/DiplomskiHbbTV/realization/HbbTV_Test/HbbTV_Test.sim/sim_1/behav/xsim.dir/FlashTest_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/DiplomskiHbbTV/realization/HbbTV_Test/HbbTV_Test.sim/sim_1/behav/xsim.dir/FlashTest_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/DiplomskiHbbTV/realization/HbbTV_Test/HbbTV_Test.sim/sim_1/behav/xsim.dir/FlashTest_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
